name: geopandas
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.3
  - six
  - cython
  # required
  - pandas
  - shapely
  - fiona
  # testing
  - pytest
  - pytest-cov
  - mypy==0.730
  #- codecov
  # optional
  - rtree
  - matplotlib
  - descartes
  #- geopy
  - SQLalchemy
  - psycopg2
  - libspatialite
  - pip
  - pip:
    - codecov
    - geopy
    - mapclassify
    - pyproj=2.4.0
    - black
    - flake8
